// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkRzIHxD3wNDiMEHGTWG-GGZ_cxCGj08',
    appId: '1:688230618783:web:d03315a6ec33a9784eb4aa',
    messagingSenderId: '688230618783',
    projectId: 'todo-app-a1d53',
    authDomain: 'todo-app-a1d53.firebaseapp.com',
    databaseURL: 'https://todo-app-a1d53-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a1d53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPabalEyiFTBk4Y6rTHwf6u0cXx4_lj0',
    appId: '1:688230618783:android:a2e8558b6d0e81c84eb4aa',
    messagingSenderId: '688230618783',
    projectId: 'todo-app-a1d53',
    databaseURL: 'https://todo-app-a1d53-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a1d53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1vr4_OcF8Liv4uPxG0JpjfjNK6v6b6l8',
    appId: '1:688230618783:ios:cbd1e8fc5e167cdd4eb4aa',
    messagingSenderId: '688230618783',
    projectId: 'todo-app-a1d53',
    databaseURL: 'https://todo-app-a1d53-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a1d53.firebasestorage.app',
    iosClientId: '688230618783-um9kbj00qn70tfmsie9p23e10dlacvmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1vr4_OcF8Liv4uPxG0JpjfjNK6v6b6l8',
    appId: '1:688230618783:ios:cbd1e8fc5e167cdd4eb4aa',
    messagingSenderId: '688230618783',
    projectId: 'todo-app-a1d53',
    databaseURL: 'https://todo-app-a1d53-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a1d53.firebasestorage.app',
    iosClientId: '688230618783-um9kbj00qn70tfmsie9p23e10dlacvmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbkRzIHxD3wNDiMEHGTWG-GGZ_cxCGj08',
    appId: '1:688230618783:web:ec193cc16ea113c14eb4aa',
    messagingSenderId: '688230618783',
    projectId: 'todo-app-a1d53',
    authDomain: 'todo-app-a1d53.firebaseapp.com',
    databaseURL: 'https://todo-app-a1d53-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-a1d53.firebasestorage.app',
  );

}